### ISSUE TITLE
Setting output file name

### ISSUE THREAD

**Issue by guille-maggio** [mdkrieg/node-red-contrib-json2excel#1]
Hey great Node! 
Just a comment, I've been struggling trying to change the output path via msg.filename as the docs said, but I was able to do it through msg.filepath. 
Again, very useful node! Best regards

**Comment by mdkrieg** [comment]
Glad you found it useful. And you are correct, I've updated the node HTML docs and the readme to refer to "filepath".

Thanks for the input!
