### ISSUE TITLE
Question- How would you add data to an existing spreadsheet?

### ISSUE THREAD

**Issue by SteveRMann** [mdkrieg/node-red-contrib-json2excel#2]

**Comment by SteveRMann** [comment]
I am generating a log file in CSV and this node may make it easier in that I won't have to import a csv file into excel.
Do you have a method for appending data to an existing spreadsheet?
Alternately, I will write a function to read the CSV file and build the JSON data.

**Comment by mdkrieg** [comment]
Hi, sorry I missed this, guess I need to watch this a little closer.

Anyway, there's no read ability on this node but it looks like you could pair it with this project to do what you want: https://flows.nodered.org/node/node-red-contrib-spreadsheet-in

Hope that helps.
