### ISSUE TITLE
Is it possible to specify the format (e.g. date, time, etc.) when exporting JSON to Excel?

### ISSUE THREAD

**Issue by SamSick** [mdkrieg/node-red-contrib-json2excel#3]

**Comment by mdkrieg** [comment]
It's possible in the parent dependency ([xlsx](https://www.npmjs.com/package/xlsx)), but not currently a feature of this package.

I'll take it as a feature request if I get time to work on this.

**Comment by SamSick** [comment]
Thanks for the answer, so my question is answered.
